apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}

    spec:
      containers:
        - name: kyma-lab

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: {{ .Values.service.port }}

          env:
            - name: PY_TEST_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: PY_TEST_LOG_LEVEL